const PDFDocument = require('pdfkit');

/**
 * Generates a beautiful professional PDF invoice and pipes it to the HTTP response.
 */
const generateBillPDF = (res, data) => {
  const doc = new PDFDocument({ margin: 50, size: 'A4' });

  // Pipe to response
  doc.pipe(res);

  // Styling Constants
  const primaryColor = '#1e293b'; // slate 800
  const secondaryColor = '#0f766e'; // teal 700
  const lightBgColor = '#f8fafc'; // slate 50
  const borderLight = '#cbd5e1'; // slate 300

  // 1. Header (Company Logo Placeholder & Invoice Info)
  doc
    .fillColor(secondaryColor)
    .fontSize(22)
    .text('GAS DISTRIBUTION ENTERPRISE', 50, 50, { bold: true })
    .fontSize(10)
    .fillColor(primaryColor)
    .text('Premium Cylinder Supply & Logistics', 50, 75)
    .text('Farm Storage Yard, City Junction', 50, 90)
    .text('Contact: +91 98765 43210 | support@gasdistribution.com', 50, 105);

  // Metadata block (Right side)
  doc
    .fontSize(12)
    .fillColor(secondaryColor)
    .text('INVOICE / LEDGER STATEMENT', 350, 50, { align: 'right', bold: true })
    .fontSize(9)
    .fillColor(primaryColor)
    .text(`Date: ${new Date().toLocaleDateString()}`, 350, 70, { align: 'right' })
    .text(`Invoice Status: ${data.pending <= 0 ? 'PAID' : 'PENDING'}`, 350, 85, { align: 'right' });

  // Divider Line
  doc.moveTo(50, 130).lineTo(545, 130).stroke(borderLight);

  // 2. Client Details (Hotel Info)
  doc
    .fontSize(11)
    .fillColor(secondaryColor)
    .text('STATEMENT ISSUED TO:', 50, 150, { bold: true })
    .fontSize(12)
    .fillColor(primaryColor)
    .text(data.hotelName.toUpperCase(), 50, 165, { bold: true })
    .fontSize(9)
    .text(`Delivery Location: ${data.address || 'Local City Distribution Area'}`, 50, 185)
    .text(`Contact: ${data.contact || 'Registered Phone Contact'}`, 50, 200);

  // Summary box (Right side)
  doc
    .rect(320, 145, 225, 75)
    .fill(lightBgColor)
    .stroke(borderLight);

  doc
    .fillColor(secondaryColor)
    .fontSize(10)
    .text('ACCOUNTS RECEIVABLE SUMMARY', 330, 155, { bold: true })
    .fillColor(primaryColor)
    .fontSize(9)
    .text(`Standard Cylinders Rate: Rs. ${data.rate} / Cylinder`, 330, 175)
    .text(`Credit Pool Balance: Rs. ${data.pending}`, 330, 195, { bold: true });

  // Space before main details
  doc.y = 240;

  // 3. Statement Summary Table Header
  const tableTop = 240;
  doc
    .rect(50, tableTop, 495, 25)
    .fill(secondaryColor);

  doc
    .fillColor('#ffffff')
    .fontSize(10)
    .text('Description', 60, tableTop + 7, { bold: true })
    .text('Cylinders Delivered', 230, tableTop + 7, { bold: true })
    .text('Rate', 360, tableTop + 7, { bold: true })
    .text('Subtotal', 460, tableTop + 7, { bold: true });

  // 4. Table Row
  const rowTop = tableTop + 25;
  doc
    .rect(50, rowTop, 495, 30)
    .fill(lightBgColor)
    .stroke(borderLight);

  doc
    .fillColor(primaryColor)
    .fontSize(9.5)
    .text('LPG Refill Cylinders (Standard Supply)', 60, rowTop + 10)
    .text(`${data.totalCylinders || 0} Units`, 230, rowTop + 10)
    .text(`Rs. ${data.rate}`, 360, rowTop + 10)
    .text(`Rs. ${data.totalAmount}`, 460, rowTop + 10, { bold: true });

  // 5. Grand Totals Table
  const totalBoxTop = rowTop + 60;
  
  doc.rect(300, totalBoxTop, 245, 95).stroke(borderLight);

  doc
    .fontSize(9.5)
    .text('Total Invoice Cost:', 310, totalBoxTop + 12)
    .text(`Rs. ${data.totalAmount}`, 450, totalBoxTop + 12, { align: 'right' });

  doc
    .fillColor('#15803d') // Green
    .text('Total Settled Amount:', 310, totalBoxTop + 37, { bold: true })
    .text(`Rs. ${data.paid}`, 450, totalBoxTop + 37, { align: 'right', bold: true });

  doc
    .fillColor(data.pending > 0 ? '#be123c' : '#15803d') // Rose / Green
    .fontSize(10.5)
    .text('Outstanding Dues:', 310, totalBoxTop + 67, { bold: true })
    .text(`Rs. ${data.pending}`, 450, totalBoxTop + 67, { align: 'right', bold: true });

  // 6. Signatures and Footer
  const footerTop = 450;
  doc.moveTo(50, footerTop).lineTo(545, footerTop).stroke(borderLight);

  doc
    .fillColor(primaryColor)
    .fontSize(9)
    .text('Terms & Operations Info:', 50, footerTop + 15, { bold: true })
    .text('1. Please verify cylinder physical seals before rickshaw release.', 50, footerTop + 30)
    .text('2. Payments are recorded immediately in the double-entry accounting ledger system.', 50, footerTop + 45)
    .text('3. Outstanding cylinder empties must be returned within 14 business days.', 50, footerTop + 60);

  // Signatures
  doc
    .fontSize(9.5)
    .text('Prepared By: Autogenerated ERP Systems', 350, footerTop + 30)
    .text('Authorized Distribution Officer', 350, footerTop + 75, { bold: true });

  doc.end();
};

module.exports = { generateBillPDF };
